# Generated by Django 4.2 on 2024-05-07 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0003_rename_link_post_url_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='points',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorite',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
