# Generated by Django 4.2 on 2024-05-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
