# Generated by Django 4.2 on 2024-05-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_post_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
