# Generated by Django 4.2 on 2024-05-08 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0010_remove_post_bookmark_post_bookmarked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
